export const list = {
  statusCode: 0,
  data: {
    cacheExpiryTime: 320,
    pages: 12,
    pageIndex: 0,
    scrubber: 0,
    configs: {
      ribbons: {
        PREORDER: {
          type: "PREORDER",
          text: "Preorder",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 3,
        },
        EXCLUSIVE: {
          type: "EXCLUSIVE",
          text: "Exclusive",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 2,
        },
        NEW: {
          type: "NEW",
          text: "Newly Added",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 4,
        },
        REPEAT: {
          type: "REPEAT",
          text: "Repeat",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#D53D4C",
          bottomBackgroundColor: "#B02331",
          priority: 6,
        },
        CLOUD: {
          type: "CLOUD",
          text: "Daily Menus",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 5,
        },
        PREMIUM: {
          type: "PREMIUM",
          text: "Premium",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#8a584b",
          bottomBackgroundColor: "#583229",
          priority: 7,
        },
        PROMOTED: {
          type: "PROMOTED",
          text: "Promoted",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#3a3c41",
          bottomBackgroundColor: "#1e2023",
          priority: 1,
        },
      },
    },
    totalSize: 178,
    currentOffset: 0,
    cards: [
      {
        cardType: "messageCard",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "messageCard",
          data: {
            message: "All Offers (177)",
          },
          subtype: "info",
          sticky: 1,
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "87812",
            name: "72BIRYANIs",
            uuid: "4c8bfb55-6744-43ff-94fa-4ca6d4962a47",
            city: "20",
            area: "Mvp Colony",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "xa3is7l6koi8erklilxx",
            cuisines: ["Biryani", "Chinese", "Beverages", "Indian"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 26,
            minDeliveryTime: 26,
            maxDeliveryTime: 26,
            slaString: "26 MINS",
            lastMileTravel: 3,
            slugs: {
              restaurant: "72-the-gaming-lounge-cafe-sector-6-mvp-colony",
              city: "vizag",
            },
            cityState: "20",
            address:
              "Sector 2, MVP Colony, Visakhapatnam, Andhra Pradesh 530017, India",
            locality: "MVP Sector 2",
            parentId: 387753,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "FLAT125 off",
              shortDescriptionList: [
                {
                  meta: "FLAT125 off | Use FLATDEAL",
                  discountType: "Flat",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "FLAT125 off | Use FLATDEAL",
                  discountType: "Flat",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "₹125 OFF",
              shortDescriptionList: [
                {
                  meta: "Use FLATDEAL",
                  discountType: "Flat",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "FLAT125 off | Use FLATDEAL",
                  discountType: "Flat",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            ribbon: [
              {
                type: "PROMOTED",
              },
            ],
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 2600,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 2600,
              message: "",
              title: "Delivery Charge",
              amount: "2600",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
              "cid=5617618~p=1~eid=00000185-b642-8c51-4104-a9f900af013a",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "3 kms",
            hasSurge: false,
            sla: {
              restaurantId: "87812",
              deliveryTime: 26,
              minDeliveryTime: 26,
              maxDeliveryTime: 26,
              lastMileTravel: 3,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "3.4",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "67848",
            name: "Satyam Restaurant",
            uuid: "dcdfe00c-5c5b-4e8f-9da0-452978291cc1",
            city: "20",
            area: "Dondaparthy",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "lg5js5h8ep5qvskfys97",
            cuisines: [
              "Biryani",
              "Chinese",
              "Tandoor",
              "North Indian",
              "Beverages",
            ],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 25,
            minDeliveryTime: 25,
            maxDeliveryTime: 25,
            slaString: "25 MINS",
            lastMileTravel: 1.2999999523162842,
            slugs: {
              restaurant: "satyam-resaturant-diamond-park-dwarka-nagar",
              city: "vizag",
            },
            cityState: "20",
            address:
              "1st Ln, Dondaparthy, Dwaraka Nagar, Visakhapatnam, Andhra Pradesh 530016",
            locality: "Dondaparthy",
            parentId: 178966,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "30% off",
              shortDescriptionList: [
                {
                  meta: "30% off | Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "30% off up to ₹75 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "30% OFF",
              shortDescriptionList: [
                {
                  meta: "Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "30% off up to ₹75 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1700,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1700,
              message: "",
              title: "Delivery Charge",
              amount: "1700",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "1.2 kms",
            hasSurge: false,
            sla: {
              restaurantId: "67848",
              deliveryTime: 25,
              minDeliveryTime: 25,
              maxDeliveryTime: 25,
              lastMileTravel: 1.2999999523162842,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "107157",
            name: "Eaters Stop",
            uuid: "c0baa07a-858b-4163-ab0f-086f0c9ab97b",
            city: "20",
            area: "Seethammadara",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "ve5gfzcuju4qkyivinqc",
            cuisines: [
              "Biryani",
              "South Indian",
              "North Indian",
              "Tandoor",
              "Chinese",
              "Lebanese",
            ],
            tags: [],
            costForTwo: 35000,
            costForTwoString: "₹350 FOR TWO",
            deliveryTime: 26,
            minDeliveryTime: 26,
            maxDeliveryTime: 26,
            slaString: "26 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
              restaurant:
                "eaters-stop-non-veg-restaurant-akkayapalem-dwarka-nagar",
              city: "vizag",
            },
            cityState: "20",
            address:
              "HP PETROL BUNK, 4th Town Police Station, 49-53-1-3/6, Beside, NH16, Visakhapatnam, Andhra Pradesh 530013, India",
            locality: "Balayya Sastri Layout",
            parentId: 12347,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "60% off",
              shortDescriptionList: [
                {
                  meta: "60% off | Use SWIGGYIT",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "60% off up to ₹120 | Use code SWIGGYIT",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "60% OFF",
              shortDescriptionList: [
                {
                  meta: "Use SWIGGYIT",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "60% off up to ₹120 | Use code SWIGGYIT",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1900,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
              restaurantId: "107157",
              deliveryTime: 26,
              minDeliveryTime: 26,
              maxDeliveryTime: 26,
              lastMileTravel: 0.8999999761581421,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 10000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "67677",
            name: "Spicy Paradise",
            uuid: "616484db-83a1-4d19-ab67-dd5038556e16",
            city: "20",
            area: "Beside Jagadamba Theater",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "earyjf7oasozqrctnath",
            cuisines: ["Biryani", "North Indian", "Chinese", "Tandoor"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 30,
            minDeliveryTime: 30,
            maxDeliveryTime: 40,
            slaString: "30-40 MINS",
            lastMileTravel: 2.700000047683716,
            slugs: {
              restaurant: "spicy-paradise-chitralaya-mall-jagadamba-junction",
              city: "vizag",
            },
            cityState: "20",
            address:
              "Door No. 28-2-54 BESIDE JAGADAMBA THEATER JAGADAMBA JUNCTION, VISAKHAPATNAM, 530002.",
            locality: "Beside Jagadamba Theater",
            parentId: 13072,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "40% off",
              shortDescriptionList: [
                {
                  meta: "40% off | Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "40% off up to ₹80 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "40% OFF",
              shortDescriptionList: [
                {
                  meta: "Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "40% off up to ₹80 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            ribbon: [
              {
                type: "PROMOTED",
              },
            ],
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1900,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
              "cid=5617905~p=4~eid=00000185-b642-8c51-4104-a9fa00af0423",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "2.7 kms",
            hasSurge: false,
            sla: {
              restaurantId: "67677",
              deliveryTime: 30,
              minDeliveryTime: 30,
              maxDeliveryTime: 40,
              lastMileTravel: 2.700000047683716,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "3.9",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "67849",
            name: "Sri Sairam Parlour - Diamond Park",
            uuid: "b564f998-6bce-4489-95d7-84cb1706728e",
            city: "20",
            area: "Railway New Colony",
            totalRatingsString: "5000+ ratings",
            cloudinaryImageId: "zjvnn12mxuojutipvsgb",
            cuisines: [
              "South Indian",
              "Chinese",
              "Tandoor",
              "Juices",
              "Sweets",
              "Beverages",
            ],
            tags: [],
            costForTwo: 15000,
            costForTwoString: "₹150 FOR TWO",
            deliveryTime: 25,
            minDeliveryTime: 25,
            maxDeliveryTime: 25,
            slaString: "25 MINS",
            lastMileTravel: 1.2999999523162842,
            slugs: {
              restaurant:
                "sri-sairam-parlour-diamond-park-diamond-park-dwarka-nagar",
              city: "vizag",
            },
            cityState: "20",
            address:
              "Opposite Diamond Park, Dondaparthy, Dwaraka Nagar, Visakhapatnam, Andhra Pradesh 530016",
            locality: "Diamond Park",
            parentId: 12846,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "20% off",
              shortDescriptionList: [
                {
                  meta: "20% off | Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "20% off up to ₹50 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "20% OFF",
              shortDescriptionList: [
                {
                  meta: "Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "20% off up to ₹50 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1900,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "1.2 kms",
            hasSurge: false,
            sla: {
              restaurantId: "67849",
              deliveryTime: 25,
              minDeliveryTime: 25,
              maxDeliveryTime: 25,
              lastMileTravel: 1.2999999523162842,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.3",
            totalRatings: 5000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "66463",
            name: "New Satyam Multicuisine Restaurant & Takeaway",
            uuid: "78af0222-75b3-45a5-b61a-c63e4e51f63b",
            city: "20",
            area: "Railway New Colony",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "gqxblfxnitdam2w3r6un",
            cuisines: ["Biryani", "Chinese", "Indian", "Tandoor", "Beverages"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            slaString: "23 MINS",
            lastMileTravel: 1.2999999523162842,
            slugs: {
              restaurant: "new-satyam-restaurant-dwarka-nagar-dwarka-nagar",
              city: "vizag",
            },
            cityState: "20",
            address:
              "47-12-1, Behind Sangam Sarat Theatre, Dondaparthy, Dwaraka Nagar, Visakhapatnam, Andhra Pradesh 530016",
            locality: "Dondaparthy",
            parentId: 372748,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "40% off",
              shortDescriptionList: [
                {
                  meta: "40% off | Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "40% off up to ₹80 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "40% OFF",
              shortDescriptionList: [
                {
                  meta: "Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "40% off up to ₹80 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1700,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1700,
              message: "",
              title: "Delivery Charge",
              amount: "1700",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "Closes soon",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "1.2 kms",
            hasSurge: false,
            sla: {
              restaurantId: "66463",
              deliveryTime: 23,
              minDeliveryTime: 23,
              maxDeliveryTime: 23,
              lastMileTravel: 1.2999999523162842,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.9",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "145737",
            name: "Burger King",
            uuid: "ac738c06-bfac-4d78-a4b2-bee541450dbf",
            city: "20",
            area: "Dwaraka Nagar",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "rlsygwumwnubw5fgshcp",
            cuisines: ["Burgers", "American"],
            tags: [],
            costForTwo: 35000,
            costForTwoString: "₹350 FOR TWO",
            deliveryTime: 38,
            minDeliveryTime: 38,
            maxDeliveryTime: 38,
            slaString: "38 MINS",
            lastMileTravel: 1.2000000476837158,
            slugs: {
              restaurant: "burger-king-maddilapalem-dwarka-nagar",
              city: "vizag",
            },
            cityState: "20",
            address:
              "Burger King,Cmr central 4th floor,Maddilapalem,Cmr central 4th floor,Maddilapalem,visakhapatnam pin code 530013",
            locality: "CMR Central",
            parentId: 166,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "60% off",
              shortDescriptionList: [
                {
                  meta: "60% off | Use STEALDEAL",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "60% off up to ₹120 | Use code STEALDEAL",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "60% OFF",
              shortDescriptionList: [
                {
                  meta: "Use STEALDEAL",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "60% off up to ₹120 | Use code STEALDEAL",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1700,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1700,
              message: "",
              title: "Delivery Charge",
              amount: "1700",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "1.2 kms",
            hasSurge: false,
            sla: {
              restaurantId: "145737",
              deliveryTime: 38,
              minDeliveryTime: 38,
              maxDeliveryTime: 38,
              lastMileTravel: 1.2000000476837158,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "182954",
            name: "New Satyam Ritz Comfort",
            uuid: "",
            city: "20",
            area: "Dwarka Nagar",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "flwo6wsjteu93durtrty",
            cuisines: ["Biryani", "Indian", "Chinese"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 24,
            minDeliveryTime: 24,
            maxDeliveryTime: 24,
            slaString: "24 MINS",
            lastMileTravel: 1.5,
            slugs: {
              restaurant: "lily-restaurant-hotel-supine-comforts-dwarka-nagar",
              city: "vizag",
            },
            cityState: "20",
            address:
              "ABR Tower 47-10-2 Railway New Colony Road, near Diamond Park Road, Dwaraka Nagar, Visakhapatnam, Andhra Pradesh 530016",
            locality: "Near Diamond Park Road",
            parentId: 17957,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "30% off",
              shortDescriptionList: [
                {
                  meta: "30% off | Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "30% off up to ₹75 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "30% OFF",
              shortDescriptionList: [
                {
                  meta: "Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "30% off up to ₹75 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1900,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "1.5 kms",
            hasSurge: false,
            sla: {
              restaurantId: "182954",
              deliveryTime: 24,
              minDeliveryTime: 24,
              maxDeliveryTime: 24,
              lastMileTravel: 1.5,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "303805",
            name: "NIC Ice Creams",
            uuid: "d7994d28-61c4-4755-ae08-877d2442133c",
            city: "20",
            area: "Mahaarajupeta",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "t2q70jw3wmrmkxlla5ll",
            cuisines: ["Ice Cream", "Desserts"],
            tags: [],
            costForTwo: 12000,
            costForTwoString: "₹120 FOR TWO",
            deliveryTime: 28,
            minDeliveryTime: 25,
            maxDeliveryTime: 35,
            slaString: "25-35 MINS",
            lastMileTravel: 2.200000047683716,
            slugs: {
              restaurant: "nic-natural-ice-creams-maddilapalem-dwarka-nagar",
              city: "vizag",
            },
            cityState: "20",
            address:
              "Shop No 30-1-21/8 Puthivari Mamyam Road, DBK Railway Quarters, Allipuram, Dabagarden, Vishakhapatnam, Andhra Pradesh-530020",
            locality: "Maddilapalem",
            parentId: 6249,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "50% off",
              shortDescriptionList: [
                {
                  meta: "50% off | Use SWIGGYIT",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "50% off up to ₹100 on select items | Use code SWIGGYIT",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "50% OFF",
              shortDescriptionList: [
                {
                  meta: "Use SWIGGYIT",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "50% off up to ₹100 on select items | Use code SWIGGYIT",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            ribbon: [
              {
                type: "PROMOTED",
              },
            ],
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1700,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1700,
              message: "",
              title: "Delivery Charge",
              amount: "1700",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
              "cid=5731601~p=10~eid=00000185-b642-8c51-4104-a9fc00af0a45",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "2.2 kms",
            hasSurge: false,
            sla: {
              restaurantId: "303805",
              deliveryTime: 28,
              minDeliveryTime: 25,
              maxDeliveryTime: 35,
              lastMileTravel: 2.200000047683716,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.5",
            totalRatings: 100,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "224899",
            name: "Swap",
            uuid: "ae7050e4-2471-4416-9c3a-aa672a3807f1",
            city: "20",
            area: "Pedda Waltair",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "h2ixcea3lev2xexab0q0",
            cuisines: ["Healthy Food", "Keto", "Salads"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 25,
            minDeliveryTime: 25,
            maxDeliveryTime: 25,
            slaString: "25 MINS",
            lastMileTravel: 2.799999952316284,
            slugs: {
              restaurant: "swap-mvp-colony-mvp-colony",
              city: "vizag",
            },
            cityState: "20",
            address:
              "Basement,Below Karur Vysya Bank,Door No.8-2-6/4,Ninithaas Highs,Pedawaltair Main Road,Visakhapatnam-530017",
            locality: "Peda Waltair Main Road",
            parentId: 12340,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "20% off",
              shortDescriptionList: [
                {
                  meta: "20% off | Use JUMBO",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "20% off up to ₹100 on orders above ₹479 | Use code JUMBO",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "20% OFF",
              shortDescriptionList: [
                {
                  meta: "Use JUMBO",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "20% off up to ₹100 on orders above ₹479 | Use code JUMBO",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            ribbon: [
              {
                type: "PROMOTED",
              },
            ],
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1900,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
              "cid=5614272~p=13~eid=00000185-b642-8c51-4104-a9fd00af0d61",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "2.7 kms",
            hasSurge: false,
            sla: {
              restaurantId: "224899",
              deliveryTime: 25,
              minDeliveryTime: 25,
              maxDeliveryTime: 25,
              lastMileTravel: 2.799999952316284,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.2",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "61914",
            name: "Pizza Hut",
            uuid: "d6bc3b45-1fca-4927-aff1-cb38b9eea841",
            city: "20",
            area: "Dwaraka Nagar",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "kl6mpnxdvnwjbrozdpww",
            cuisines: ["Pizzas"],
            tags: [],
            costForTwo: 35000,
            costForTwoString: "₹350 FOR TWO",
            deliveryTime: 41,
            minDeliveryTime: 41,
            maxDeliveryTime: 41,
            slaString: "41 MINS",
            lastMileTravel: 1.2000000476837158,
            slugs: {
              restaurant: "pizza-hut-cmr-mall-dwarka-nagar",
              city: "vizag",
            },
            cityState: "20",
            address:
              "52-1-35,36 & 38, CMR Mall, New Resapuvanipalem, Maddilapalem, Visakhapatnam ? 13",
            locality: "CMR Mall",
            parentId: 721,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "40% off",
              shortDescriptionList: [
                {
                  meta: "40% off | Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "40% off up to ₹80 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "40% OFF",
              shortDescriptionList: [
                {
                  meta: "Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "40% off up to ₹80 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1700,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1700,
              message: "",
              title: "Delivery Charge",
              amount: "1700",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "1.2 kms",
            hasSurge: false,
            sla: {
              restaurantId: "61914",
              deliveryTime: 41,
              minDeliveryTime: 41,
              maxDeliveryTime: 41,
              lastMileTravel: 1.2000000476837158,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.9",
            totalRatings: 100,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "70355",
            name: "Bombay Restaurant-Jyothee Theatre",
            uuid: "09de4193-d421-462f-ad73-c6d32f52149d",
            city: "20",
            area: "Daba Gardens",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "k4jdyfukz53g5eivlbbu",
            cuisines: ["Indian", "Chinese", "Tandoor", "Biryani"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 32,
            minDeliveryTime: 30,
            maxDeliveryTime: 40,
            slaString: "30-40 MINS",
            lastMileTravel: 2.9000000953674316,
            slugs: {
              restaurant: "bombay-restaurant-allipuram-jagadamba-junction",
              city: "vizag",
            },
            cityState: "20",
            address:
              "31-32-75/4,ladies gate, Near Jothee Theatre Rd, Daba Gardens, 104 Area, Visakhapatnam, Andhra Pradesh 530020, India",
            locality: "Beside Jothee Theatre ladies gate",
            parentId: 12842,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "10% off",
              shortDescriptionList: [
                {
                  meta: "10% off | Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "10% off up to ₹40 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "10% OFF",
              shortDescriptionList: [
                {
                  meta: "Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "10% off up to ₹40 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1900,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "2.9 kms",
            hasSurge: false,
            sla: {
              restaurantId: "70355",
              deliveryTime: 32,
              minDeliveryTime: 30,
              maxDeliveryTime: 40,
              lastMileTravel: 2.9000000953674316,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.8",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "91259",
            name: "B treats Restaurant",
            uuid: "f3a2ec14-9cbb-4f2c-bdba-39f042155e9e",
            city: "20",
            area: "Seethammadara",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "qytgc1c9zu6kam5vi32q",
            cuisines: [
              "South Indian",
              "North Indian",
              "Biryani",
              "Tandoor",
              "Chinese",
            ],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 27,
            minDeliveryTime: 27,
            maxDeliveryTime: 27,
            slaString: "27 MINS",
            lastMileTravel: 1.2000000476837158,
            slugs: {
              restaurant: "b-treats-restaurant-seethammadhara-dwarka-nagar",
              city: "vizag",
            },
            cityState: "20",
            address:
              "45-B/3 Next to More Supermarket, Balayya Sastri Layout, Seethammadara, Visakhapatnam, Andhra Pradesh 530013, India",
            locality: "Seethamadhara",
            parentId: 18222,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "FLAT75 off",
              shortDescriptionList: [
                {
                  meta: "FLAT75 off | Use SNACKSBINGE",
                  discountType: "Flat",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "FLAT75 off | Use SNACKSBINGE",
                  discountType: "Flat",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "₹75 OFF",
              shortDescriptionList: [
                {
                  meta: "Use SNACKSBINGE",
                  discountType: "Flat",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "FLAT75 off | Use SNACKSBINGE",
                  discountType: "Flat",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            ribbon: [
              {
                type: "PROMOTED",
              },
            ],
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1900,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
              "cid=5684193~p=16~eid=00000185-b642-8c51-4104-a9fe00af107b",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "1.2 kms",
            hasSurge: false,
            sla: {
              restaurantId: "91259",
              deliveryTime: 27,
              minDeliveryTime: 27,
              maxDeliveryTime: 27,
              lastMileTravel: 1.2000000476837158,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "3.8",
            totalRatings: 100,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "61675",
            name: "Real Deepak Punjabi Dhaba",
            uuid: "3a2eccf3-bbbe-4ad2-8efd-bfc03f932615",
            city: "20",
            area: "Seethammadara",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "nthkkxujjleirngkcnlt",
            cuisines: ["Indian", "Chinese", "Seafood", "Mughlai"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            slaString: "23 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
              restaurant:
                "real-deepak-punjabi-dhaba-seethammadhara-dwarka-nagar",
              city: "vizag",
            },
            cityState: "20",
            address:
              "1st Floor, Opp Kiran hospital, TPT Colony, Balayya Sastri Layout, Seethammadara, Visakhapatnam, Andhra Pradesh 530013",
            locality: "TPT Colony",
            parentId: 5191,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "10% off",
              shortDescriptionList: [
                {
                  meta: "10% off | Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "10% off up to ₹40 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "10% OFF",
              shortDescriptionList: [
                {
                  meta: "Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "10% off up to ₹40 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                {
                  name: "distance",
                  fee: 1900,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
              imageBased: [],
              textBased: [],
              textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
              restaurantId: "61675",
              deliveryTime: 23,
              minDeliveryTime: 23,
              maxDeliveryTime: 23,
              lastMileTravel: 0.8999999761581421,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 500,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
    ],
    nextPageFetch: 0,
  },
  tid: "0680fb17-17f9-4aec-9811-c41e5536507d",
  sid: "4ul4ed36-9246-4ce7-9608-9ffe5e8e33fc",
  deviceId: "2bfc90dd-7483-88b1-308d-288e85e14364",
  csrfToken: "S44eKZSHsHDS--AdipTwYOlT7B9UQKElqCu2RzSM",
};


export const imageURL = `https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/`